"""The destinations RuDi knows about (M9, ADR-0017).

Cities and towns, with a centre and a box wide enough to hold the part people
mean when they say the name. Geography, not business data: a city's name and
its coordinates are public facts, so unlike the venues inside them these rows
live in Git and are the input the OpenStreetMap import queries with.

Boxes are deliberately tight around the visited core rather than around the
administrative boundary. «Đà Lạt» to somebody planning a weekend means the
lake and the streets around it, not the whole district; a box drawn on the
boundary would pull in a hundred roadside shops nobody is asking about.
"""

from __future__ import annotations

from typing import Any

DESTINATIONS_VN: list[dict[str, Any]] = [
    {
        "id": "d-da-lat",
        "name": "Đà Lạt",
        "province": "Lâm Đồng",
        "lat": 11.9404,
        "lng": 108.4583,
        "bbox_south": 11.88,
        "bbox_west": 108.38,
        "bbox_north": 12.00,
        "bbox_east": 108.52,
        "blurb": "Thành phố sương mù, quán cà phê và đồi thông.",
        "sort_order": 10,
    },
    {
        "id": "d-tphcm",
        "name": "TP. Hồ Chí Minh",
        "province": "TP. Hồ Chí Minh",
        "lat": 10.7769,
        "lng": 106.7009,
        "bbox_south": 10.72,
        "bbox_west": 106.65,
        "bbox_north": 10.83,
        "bbox_east": 106.75,
        "blurb": "Ăn khuya, rooftop và cà phê vợt trong hẻm.",
        "sort_order": 20,
    },
    {
        "id": "d-ha-noi",
        "name": "Hà Nội",
        "province": "Hà Nội",
        "lat": 21.0285,
        "lng": 105.8542,
        "bbox_south": 20.98,
        "bbox_west": 105.81,
        "bbox_north": 21.07,
        "bbox_east": 105.90,
        "blurb": "Phố cổ, bún chả, cà phê trứng và hồ Tây.",
        "sort_order": 30,
    },
    {
        "id": "d-da-nang",
        "name": "Đà Nẵng",
        "province": "Đà Nẵng",
        "lat": 16.0544,
        "lng": 108.2022,
        "bbox_south": 16.00,
        "bbox_west": 108.15,
        "bbox_north": 16.12,
        "bbox_east": 108.28,
        "blurb": "Biển Mỹ Khê, cầu Rồng, hải sản và cà phê view sông.",
        "sort_order": 40,
    },
    {
        "id": "d-hoi-an",
        "name": "Hội An",
        "province": "Quảng Nam",
        "lat": 15.8801,
        "lng": 108.3380,
        "bbox_south": 15.85,
        "bbox_west": 108.30,
        "bbox_north": 15.92,
        "bbox_east": 108.39,
        "blurb": "Phố đèn lồng, cao lầu, sông Hoài và làng rau Trà Quế.",
        "sort_order": 50,
    },
    {
        "id": "d-nha-trang",
        "name": "Nha Trang",
        "province": "Khánh Hòa",
        "lat": 12.2388,
        "lng": 109.1967,
        "bbox_south": 12.19,
        "bbox_west": 109.16,
        "bbox_north": 12.29,
        "bbox_east": 109.24,
        "blurb": "Biển dài, bún cá, và quán đêm dọc Trần Phú.",
        "sort_order": 60,
    },
    {
        "id": "d-hue",
        "name": "Huế",
        "province": "Thừa Thiên Huế",
        "lat": 16.4637,
        "lng": 107.5909,
        "bbox_south": 16.42,
        "bbox_west": 107.54,
        "bbox_north": 16.51,
        "bbox_east": 107.64,
        "blurb": "Kinh thành, sông Hương, bún bò và chè.",
        "sort_order": 70,
    },
    {
        "id": "d-sa-pa",
        "name": "Sa Pa",
        "province": "Lào Cai",
        "lat": 22.3364,
        "lng": 103.8438,
        "bbox_south": 22.29,
        "bbox_west": 103.80,
        "bbox_north": 22.38,
        "bbox_east": 103.89,
        "blurb": "Ruộng bậc thang, chợ vùng cao và sương mù.",
        "sort_order": 80,
    },
    {
        "id": "d-phu-quoc",
        "name": "Phú Quốc",
        "province": "Kiên Giang",
        "lat": 10.2270,
        "lng": 103.9640,
        "bbox_south": 10.15,
        "bbox_west": 103.90,
        "bbox_north": 10.35,
        "bbox_east": 104.06,
        "blurb": "Biển đảo, chợ đêm và hải sản.",
        "sort_order": 90,
    },
    {
        "id": "d-vung-tau",
        "name": "Vũng Tàu",
        "province": "Bà Rịa - Vũng Tàu",
        "lat": 10.3460,
        "lng": 107.0843,
        "bbox_south": 10.31,
        "bbox_west": 107.05,
        "bbox_north": 10.40,
        "bbox_east": 107.13,
        "blurb": "Biển gần Sài Gòn, bánh khọt và tượng Chúa.",
        "sort_order": 100,
    },
    {
        "id": "d-can-tho",
        "name": "Cần Thơ",
        "province": "Cần Thơ",
        "lat": 10.0452,
        "lng": 105.7469,
        "bbox_south": 10.01,
        "bbox_west": 105.71,
        "bbox_north": 10.08,
        "bbox_east": 105.80,
        "blurb": "Chợ nổi Cái Răng, bến Ninh Kiều, lẩu mắm.",
        "sort_order": 110,
    },
    {
        "id": "d-ha-long",
        "name": "Hạ Long",
        "province": "Quảng Ninh",
        "lat": 20.9515,
        "lng": 107.0748,
        "bbox_south": 20.91,
        "bbox_west": 107.02,
        "bbox_north": 21.00,
        "bbox_east": 107.14,
        "blurb": "Vịnh đá vôi, hải sản và du thuyền.",
        "sort_order": 120,
    },
    {
        "id": "d-quy-nhon",
        "name": "Quy Nhơn",
        "province": "Bình Định",
        "lat": 13.7829,
        "lng": 109.2196,
        "bbox_south": 13.74,
        "bbox_west": 109.18,
        "bbox_north": 13.82,
        "bbox_east": 109.27,
        "blurb": "Biển vắng, bánh xèo tôm nhảy, tháp Chăm.",
        "sort_order": 130,
    },
    {
        "id": "d-ninh-binh",
        "name": "Ninh Bình",
        "province": "Ninh Bình",
        "lat": 20.2506,
        "lng": 105.9745,
        "bbox_south": 20.18,
        "bbox_west": 105.90,
        "bbox_north": 20.32,
        "bbox_east": 106.03,
        "blurb": "Tràng An, Tam Cốc, núi đá và ruộng lúa.",
        "sort_order": 140,
    },
    {
        "id": "d-mui-ne",
        "name": "Mũi Né",
        "province": "Bình Thuận",
        "lat": 10.9330,
        "lng": 108.2870,
        "bbox_south": 10.90,
        "bbox_west": 108.22,
        "bbox_north": 10.97,
        "bbox_east": 108.35,
        "blurb": "Đồi cát, biển gió và hải sản.",
        "sort_order": 150,
    },
]

DESTINATION_BY_ID = {row["id"]: row for row in DESTINATIONS_VN}
