"""Export golden allocator vectors as fixtures the mobile app can replay.

Why this script exists at all: the app once carried its own split, written in
TypeScript, in the same file whose docstring said "Nothing here computes money".
That was a second allocator implementation and it divided with `/`, producing
float intermediates -- both forbidden. A demo that shows a number it computed
itself is a demo that can disagree with the server about money.

So the fake stops computing and starts replaying. Every fixture below is an
answer the real Python allocator produced for a vector that was computed by
hand first, which makes this file a projection of the existing oracle rather
than a second source of truth. Regenerate it, never hand-edit it:

    cd services/api && python3 tools/build_mobile_fixtures.py

Only vectors that are a plain even split survive the filter -- items,
surcharges and discounts have no screen in the app yet, and a fixture the UI
cannot render is a fixture nobody checks.
"""

from __future__ import annotations

import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
API = HERE.parent
sys.path.insert(0, str(API))

GOLDEN = API / "tests" / "domain" / "golden"
# Emitted as TypeScript, not JSON: Node's ESM loader demands an import
# attribute for JSON, and Metro and tsc disagree about whether that
# attribute is allowed. A .ts module is plainly readable by all three.
OUT = API.parent.parent / "apps" / "mobile" / "src" / "fixtures" / "proposals.ts"

# The corpus identifies people by single letters. The app has to show something
# a person would recognise, so map them to obviously-synthetic Vietnamese names.
# `z` exists because one vector puts the advancer OUTSIDE the participant set.
NAMES = {
    "a": "Nam",
    "b": "Hà",
    "c": "Quyên",
    "d": "Tuấn",
    "e": "Linh",
    "z": "Người ngoài nhóm",
    "á": "Ánh",
    "aa": "An",
}

OCCASIONS = {
    3: "bữa lẩu tối thứ bảy",
    2: "cà phê sáng chủ nhật",
    4: "tiền xe về Vũng Tàu",
    5: "thuê nhà nghỉ hai đêm",
}


def load_vectors() -> list[dict]:
    cases = []
    for path in sorted(GOLDEN.glob("*.json")):
        cases.extend(json.loads(path.read_text(encoding="utf-8")))
    return cases


def is_plain_even_split(case: dict) -> bool:
    supplied = case["input"]
    expected = case.get("expect", {})
    return (
        "allocations" in expected
        and not supplied.get("items")
        and not supplied.get("surcharges")
        and not supplied.get("discounts")
    )


def to_fixture(case: dict) -> dict:
    supplied = case["input"]
    expected = case["expect"]
    participants = [
        {"id": pid, "name": NAMES.get(pid, pid.upper())} for pid in supplied["participants"]
    ]
    return {
        "id": case["id"],
        "note": case["note"],
        "occasion": OCCASIONS.get(len(participants), "khoản chi chung"),
        "totalVnd": supplied["total_vnd"],
        "advancerId": supplied.get("advancer_id"),
        "participants": participants,
        "allocations": expected["allocations"],
        "roundingGainers": expected.get("rounding_gainers", []),
    }


def main() -> None:
    fixtures = [to_fixture(case) for case in load_vectors() if is_plain_even_split(case)]

    # A fixture whose parts do not add up would be worse than no fixture: it
    # would put a wrong number on screen with the authority of the corpus.
    for fixture in fixtures:
        total = sum(fixture["allocations"].values())
        if total != fixture["totalVnd"]:
            raise SystemExit(
                f"{fixture['id']}: allocations sum to {total}, expected {fixture['totalVnd']}"
            )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(fixtures, ensure_ascii=False, indent=2)
    OUT.write_text(
        "/* GENERATED by services/api/tools/build_mobile_fixtures.py -- do not edit.\n"
        " *\n"
        " * Every answer here came from the real Python allocator running a golden\n"
        " * vector that was computed by hand first. The app replays these instead of\n"
        " * splitting anything itself.\n"
        " */\n"
        "import type { Fixture } from \"../api\";\n\n"
        f"export const PROPOSAL_FIXTURES: Fixture[] = {body};\n",
        encoding="utf-8",
    )
    print(f"wrote {len(fixtures)} fixtures to {OUT.relative_to(API.parent.parent)}")


if __name__ == "__main__":
    main()
