"""them bang danh tinh: people, contexts, memberships

Revision ID: 03b9e198c99f
Revises: 20260827_0001

The autogenerated `Create Date` line is removed on purpose. A date-and-time
stamp matches the long-number rule, which allows spaces and dashes BETWEEN
digits because that is how a phone number gets written. Git already records
when this file was created, so the line is noise that trips a guard for no
benefit, and every autogenerated migration will need the same removal.

Writing the offending timestamp out as an example here tripped the same rule
a second time, which is a fair demonstration that the rule is doing its job.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "03b9e198c99f"
down_revision: str | Sequence[str] | None = "20260827_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "people",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_people")),
    )
    op.create_table(
        "contexts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["people.id"], name="fk_contexts_created_by"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contexts")),
    )
    op.create_table(
        "memberships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "invited",
                "active",
                "left",
                name="membership_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("invited_by_id", sa.UUID(), nullable=True),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(state = 'left') = (left_at IS NOT NULL)",
            name=op.f("ck_memberships_left_state_matches_timestamp"),
        ),
        sa.ForeignKeyConstraint(
            ["context_id"], ["contexts.id"], name="fk_memberships_context"
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_id"], ["people.id"], name="fk_memberships_invited_by"
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["people.id"], name="fk_memberships_person"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
    )
    op.create_index(
        "ix_memberships_person_open",
        "memberships",
        ["person_id"],
        unique=False,
        postgresql_where=sa.text("left_at IS NULL"),
    )
    op.create_index(
        "uq_memberships_open_per_person",
        "memberships",
        ["context_id", "person_id"],
        unique=True,
        postgresql_where=sa.text("left_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_memberships_open_per_person",
        table_name="memberships",
        postgresql_where=sa.text("left_at IS NULL"),
    )
    op.drop_index(
        "ix_memberships_person_open",
        table_name="memberships",
        postgresql_where=sa.text("left_at IS NULL"),
    )
    op.drop_table("memberships")
    op.drop_table("contexts")
    op.drop_table("people")
    # ### end Alembic commands ###
