"""them bang idempotency_keys

Revision ID: 6ba1d0cef47a
Revises: 03b9e198c99f

The `Create Date` line is removed on purpose; see the docstring in
03b9e198c99f for why every autogenerated migration needs the same removal.

The unique constraint on (scope, idempotency_key) is not decoration. It is the
entire mechanism: reservation is one `INSERT ... ON CONFLICT DO NOTHING`, so
exactly one caller can win a key even when several processes serve the same
retry at the same instant. Drop the constraint and the feature silently becomes
a suggestion.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6ba1d0cef47a'
down_revision: Union[str, Sequence[str], None] = '03b9e198c99f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'idempotency_keys',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('scope', sa.Text(), nullable=False),
        sa.Column('idempotency_key', sa.Text(), nullable=False),
        sa.Column('request_fingerprint', sa.Text(), nullable=False),
        sa.Column('response_status', sa.Integer(), nullable=True),
        sa.Column('response_body', sa.LargeBinary(), nullable=True),
        sa.Column('response_media_type', sa.Text(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            '(response_status IS NULL) = (completed_at IS NULL)',
            name=op.f('ck_idempotency_keys_completion_is_all_or_nothing'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_keys')),
        sa.UniqueConstraint(
            'scope', 'idempotency_key', name='uq_idempotency_keys_scope_key'
        ),
    )


def downgrade() -> None:
    op.drop_table('idempotency_keys')
