"""The declared items total is checked before anything reaches the database.

`tests/api/test_bill_items_total_matches_lines.py` proves the rule against the
fake repository. A fake can prove the answer is 422; it cannot prove that
nothing was written on the way to saying so, because its `create_bill` is a
dictionary assignment with no transaction around it.

That distinction is the whole reason this file exists. A guard placed one line
too late still returns 422 and still leaves the bill row, its items, and its
shares committed -- and the fake reports both placements as identical green.
What a reader would then see is a bill that `POST /bills` swore it had refused,
sitting in `GET /bills/{id}` with a total that contradicts its own lines: the
original defect, now with a rejection message on top.

So the assertion here is about absence, read across a real commit and a fresh
connection. Scoped to a context id generated by this test, because
`tests/postgres` shares one schema for the whole session and a count over the
whole `bills` table would be measuring every other test in the run.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime

import pytest
from sqlalchemy import func, select
from sqlalchemy.engine import Engine
from sqlalchemy.orm import Session

from app.api.deps import Actor
from app.api.errors import ApiProblem
from app.api.repository import SqlAlchemyApiRepository
from app.api.schemas import BillCreateRequest, BillItemCreateRequest
from app.api.service import ApiService
from app.db.models import (
    Bill,
    Context,
    Membership,
    MembershipRole,
    MembershipState,
    Person,
)

NOW = datetime(2030, 8, 29, 9, 0, tzinfo=UTC)
ROLES = frozenset({"member", "advancer"})

# Two lines that do not match, so an even split and a per-item split cannot
# agree by accident.
LINE_ONE_VND = 65_000
LINE_TWO_VND = 70_000
LINES_SUM_VND = LINE_ONE_VND + LINE_TWO_VND


def _person(session: Session, name: str) -> Person:
    person = Person(id=uuid.uuid4(), display_name=name)
    session.add(person)
    session.flush()
    return person


def _group_of_two(session: Session) -> tuple[uuid.UUID, Person, Person]:
    """A real context with two active members.

    Both people have to be real and active: `create_bill` runs
    `_require_participants_are_members` over every suggested id before it
    reaches the rule under test, so a thin roster would make these tests pass
    for the wrong reason.
    """
    payer = _person(session, "Nam")
    friend = _person(session, "Hà")
    context = Context(
        id=uuid.uuid4(), display_name="Nhóm ăn tối", created_by_id=payer.id
    )
    session.add(context)
    session.flush()
    for person in (payer, friend):
        session.add(
            Membership(
                id=uuid.uuid4(),
                context_id=context.id,
                person_id=person.id,
                state=MembershipState.ACTIVE,
                joined_at=NOW,
                left_at=None,
                role=MembershipRole.MEMBER,
            )
        )
    session.flush()
    return context.id, payer, friend


def _request(
    context_id: uuid.UUID,
    payer: Person,
    friend: Person,
    *,
    items_total_vnd: int,
) -> BillCreateRequest:
    return BillCreateRequest(
        context_id=context_id,
        printed_total_vnd=None,
        items_total_vnd=items_total_vnd,
        confidence=88,
        needs_review=False,
        items=[
            BillItemCreateRequest(
                item_key="i1",
                name="Phở bò",
                quantity=1,
                unit_price_vnd=LINE_ONE_VND,
                line_total_vnd=LINE_ONE_VND,
                suggested_participant_ids=[payer.id],
            ),
            BillItemCreateRequest(
                item_key="i2",
                name="Bún chả",
                quantity=1,
                unit_price_vnd=LINE_TWO_VND,
                line_total_vnd=LINE_TWO_VND,
                suggested_participant_ids=[friend.id],
            ),
        ],
        surcharges=[],
        discounts=[],
    )


def _create(session: Session, context_id, payer, friend, *, items_total_vnd):
    service = ApiService(SqlAlchemyApiRepository(session))
    return service.create_bill(
        _request(context_id, payer, friend, items_total_vnd=items_total_vnd),
        Actor(id=payer.id, roles=ROLES, context_ids=frozenset({context_id})),
    )


def _bills_in(engine: Engine, session: Session, context_id: uuid.UUID) -> int:
    """Commit, then count through a brand-new connection.

    Reading through the writing session would count rows it has merely flushed,
    which is the failure mode this file is built to detect.
    """
    session.commit()
    with Session(engine, expire_on_commit=False) as reader:
        return reader.scalar(
            select(func.count()).select_from(Bill).where(Bill.context_id == context_id)
        )


def test_a_consistent_bill_is_stored(
    postgres_engine: Engine, postgres_session: Session
):
    """The positive control. Without it, a service that refuses every bill
    satisfies both cases below."""
    context_id, payer, friend = _group_of_two(postgres_session)

    response = _create(
        postgres_session, context_id, payer, friend, items_total_vnd=LINES_SUM_VND
    )

    assert response.items_total_vnd == LINES_SUM_VND
    assert _bills_in(postgres_engine, postgres_session, context_id) == 1


def test_a_bill_that_does_not_add_up_is_refused(postgres_session: Session):
    context_id, payer, friend = _group_of_two(postgres_session)

    with pytest.raises(ApiProblem) as caught:
        _create(
            postgres_session,
            context_id,
            payer,
            friend,
            items_total_vnd=LINES_SUM_VND + 40_000,
        )

    assert caught.value.status_code == 422
    assert caught.value.code == "bill_items_total_mismatch"


def test_the_refused_bill_leaves_no_row_behind(
    postgres_engine: Engine, postgres_session: Session
):
    """The assertion the fake repository cannot make.

    If the check ever moves below `repository.create_bill`, the refusal above
    stays green and this count becomes 1 -- a bill the API said it would not
    accept, readable afterwards with a total contradicting its own lines.
    """
    context_id, payer, friend = _group_of_two(postgres_session)

    with pytest.raises(ApiProblem):
        _create(
            postgres_session,
            context_id,
            payer,
            friend,
            items_total_vnd=LINES_SUM_VND + 40_000,
        )

    assert _bills_in(postgres_engine, postgres_session, context_id) == 0
