/* GENERATED by services/api/tools/build_mobile_fixtures.py -- do not edit.
 *
 * Every answer here came from the real Python allocator running a golden
 * vector that was computed by hand first. The app replays these instead of
 * splitting anything itself.
 */
import type { Fixture } from "../api";

export const PROPOSAL_FIXTURES: Fixture[] = [
  {
    "id": "G01",
    "note": "EVEN_SPLIT chia het",
    "occasion": "bữa lẩu tối thứ bảy",
    "totalVnd": 300000,
    "advancerId": "a",
    "participants": [
      {
        "id": "a",
        "name": "Nam"
      },
      {
        "id": "b",
        "name": "Hà"
      },
      {
        "id": "c",
        "name": "Quyên"
      }
    ],
    "allocations": {
      "a": 100000,
      "b": 100000,
      "c": 100000
    },
    "roundingGainers": []
  },
  {
    "id": "G02",
    "note": "EVEN_SPLIT du 1d, advancer LA participant -> advancer nuot phan le (QD #16)",
    "occasion": "bữa lẩu tối thứ bảy",
    "totalVnd": 100000,
    "advancerId": "b",
    "participants": [
      {
        "id": "a",
        "name": "Nam"
      },
      {
        "id": "b",
        "name": "Hà"
      },
      {
        "id": "c",
        "name": "Quyên"
      }
    ],
    "allocations": {
      "a": 33333,
      "b": 33334,
      "c": 33333
    },
    "roundingGainers": [
      "b"
    ]
  },
  {
    "id": "G03",
    "note": "advancer NGOAI tap tham gia -> mat tie-break, lui ve thu tu byte (QD #7,#17)",
    "occasion": "bữa lẩu tối thứ bảy",
    "totalVnd": 100000,
    "advancerId": "z",
    "participants": [
      {
        "id": "a",
        "name": "Nam"
      },
      {
        "id": "b",
        "name": "Hà"
      },
      {
        "id": "c",
        "name": "Quyên"
      }
    ],
    "allocations": {
      "a": 33334,
      "b": 33333,
      "c": 33333
    },
    "roundingGainers": [
      "a"
    ]
  },
  {
    "id": "G04",
    "note": "deficit = 2, khong co advancer",
    "occasion": "bữa lẩu tối thứ bảy",
    "totalVnd": 100001,
    "advancerId": null,
    "participants": [
      {
        "id": "a",
        "name": "Nam"
      },
      {
        "id": "b",
        "name": "Hà"
      },
      {
        "id": "c",
        "name": "Quyên"
      }
    ],
    "allocations": {
      "a": 33334,
      "b": 33334,
      "c": 33333
    },
    "roundingGainers": [
      "a",
      "b"
    ]
  },
  {
    "id": "G05",
    "note": "total_vnd < n (QD #11). 3 dong / 5 nguoi. advancer d thang tie truoc, roi byte order",
    "occasion": "thuê nhà nghỉ hai đêm",
    "totalVnd": 3,
    "advancerId": "d",
    "participants": [
      {
        "id": "a",
        "name": "Nam"
      },
      {
        "id": "b",
        "name": "Hà"
      },
      {
        "id": "c",
        "name": "Quyên"
      },
      {
        "id": "d",
        "name": "Tuấn"
      },
      {
        "id": "e",
        "name": "Linh"
      }
    ],
    "allocations": {
      "a": 1,
      "b": 1,
      "c": 0,
      "d": 1,
      "e": 0
    },
    "roundingGainers": [
      "d",
      "a",
      "b"
    ]
  },
  {
    "id": "G06",
    "note": "total_vnd = 0 (QD #9). KHONG bao zero_share vi total = 0 (QD #21)",
    "occasion": "cà phê sáng chủ nhật",
    "totalVnd": 0,
    "advancerId": "a",
    "participants": [
      {
        "id": "a",
        "name": "Nam"
      },
      {
        "id": "b",
        "name": "Hà"
      }
    ],
    "allocations": {
      "a": 0,
      "b": 0
    },
    "roundingGainers": []
  },
  {
    "id": "G07",
    "note": "n = 1",
    "occasion": "khoản chi chung",
    "totalVnd": 12345,
    "advancerId": "a",
    "participants": [
      {
        "id": "a",
        "name": "Nam"
      }
    ],
    "allocations": {
      "a": 12345
    },
    "roundingGainers": []
  },
  {
    "id": "G16",
    "note": "THU TU BYTE UTF-8, KHONG phai collation tieng Viet (QD #17). byte: 'z'=0x7a < 'a-sac'=0xc3a1. Collation tieng Viet cho ket qua NGUOC LAI",
    "occasion": "cà phê sáng chủ nhật",
    "totalVnd": 3,
    "advancerId": null,
    "participants": [
      {
        "id": "z",
        "name": "Người ngoài nhóm"
      },
      {
        "id": "á",
        "name": "Ánh"
      }
    ],
    "allocations": {
      "z": 2,
      "á": 1
    },
    "roundingGainers": [
      "z"
    ]
  },
  {
    "id": "G17",
    "note": "thu tu INPUT bi dao -> ket qua KHONG doi (bat bien 6). Van la a nhan +1d",
    "occasion": "bữa lẩu tối thứ bảy",
    "totalVnd": 100000,
    "advancerId": null,
    "participants": [
      {
        "id": "c",
        "name": "Quyên"
      },
      {
        "id": "a",
        "name": "Nam"
      },
      {
        "id": "b",
        "name": "Hà"
      }
    ],
    "allocations": {
      "a": 33334,
      "b": 33333,
      "c": 33333
    },
    "roundingGainers": [
      "a"
    ]
  },
  {
    "id": "G26",
    "note": "THU TU PREFIX: 'a' la prefix cua 'aa' -> day NGAN HON dung truoc",
    "occasion": "cà phê sáng chủ nhật",
    "totalVnd": 3,
    "advancerId": null,
    "participants": [
      {
        "id": "a",
        "name": "Nam"
      },
      {
        "id": "aa",
        "name": "An"
      }
    ],
    "allocations": {
      "a": 2,
      "aa": 1
    },
    "roundingGainers": [
      "a"
    ]
  }
];
