/* GENERATED by services/api/tools/build_mobile_fixtures.py -- do not edit.
 *
 * Hand-written corpus cases, exported so the proposal card demonstrates
 * what the contract actually promises rather than something invented for
 * the demo. Every cited message id is checked to exist before writing.
 */
import type { Extraction, ThreadMessage } from "../extraction";

export type DemoThread = {
  id: string;
  note: string;
  messages: ThreadMessage[];
  extraction: Extraction;
};

export const DEMO_THREADS: DemoThread[] = [
  {
    "id": "01-ro-rang",
    "note": "Ca de nhat. Neu ca nay sai thi khong can xet tiep.",
    "messages": [
      {
        "id": "m1",
        "author": "Nam",
        "text": "tao vua tra tien an toi 800k nhe"
      },
      {
        "id": "m2",
        "author": "Ha",
        "text": "ok"
      }
    ],
    "extraction": {
      "expenses": [
        {
          "totalVnd": 800000,
          "paidBy": "Nam",
          "label": "an toi",
          "sourceMessageIds": [
            "m1"
          ]
        }
      ],
      "questions": [
        "ai co mat trong bua an toi"
      ]
    }
  },
  {
    "id": "11-khong-du-chac-chan",
    "note": "Ky vong dung la HOI, khong phai doan. Voi tien, doan bay te hon hoi.",
    "messages": [
      {
        "id": "m1",
        "author": "Ha",
        "text": "tien an hom qua tao tra roi day"
      },
      {
        "id": "m2",
        "author": "Nam",
        "text": "uh"
      }
    ],
    "extraction": {
      "expenses": [],
      "questions": [
        "bua an hom qua het bao nhieu tien"
      ]
    }
  },
  {
    "id": "04-noi-dua-khong-phai-khoan-chi",
    "note": "Nhom ban noi dua ve tien suot. Trich mot cau dua thanh no la loi nang nhat trong bo nay.",
    "messages": [
      {
        "id": "m1",
        "author": "Nam",
        "text": "tao no may ca ty roi day"
      },
      {
        "id": "m2",
        "author": "Ha",
        "text": "haha tra dan"
      },
      {
        "id": "m3",
        "author": "Quyen",
        "text": "tien nuoc 60k tao ung nhe"
      }
    ],
    "extraction": {
      "expenses": [
        {
          "totalVnd": 60000,
          "paidBy": "Quyen",
          "label": "tien nuoc",
          "sourceMessageIds": [
            "m3"
          ]
        }
      ],
      "questions": []
    }
  }
];
