#!/usr/bin/env python3
"""Did the test suite run on the library versions that actually ship?

`services/api/requirements-dev.txt` is what the image installs, so it is what
runs in production. It is *not* necessarily what runs `pytest` on a developer
machine, and nothing in this repository has ever compared the two.

## The measurement that produced this file

Run on 2026-08-30 against `origin/main` at 56a2c19, on the interpreter that
`scripts/gate.sh api` uses (`/home/lakiet/miniconda3/bin/python3`): of 12 pinned
packages, **5 matched, 6 drifted and 1 was absent entirely**.

    alembic     pin 1.14.0    installed 1.16.5
    fastapi     pin 0.115.6   installed 0.135.3
    jinja2      pin 3.1.5     installed 3.1.6
    pytest      pin 8.3.4     installed 9.0.3
    segno       pin 1.6.1     installed 1.6.6
    sqlalchemy  pin 2.0.36    installed 2.0.43
    pytest-subtests  pinned, NOT INSTALLED

Half the pins. The suite's 2170 green cases were produced by software that is
not the software that ships.

## Why that is a defect and not trivia

This already cost the team a day. `services/api/app/api/routes/memories.py`
declared a 204 route as `-> None`; fastapi 0.115.6 asserts at *route
registration* and refused to import the app, fastapi 0.135.3 normalises the
annotation and never reaches the assert. 2305 pytest cases were green on this
machine while the container could not boot, and the demo machine stayed dead for
hours. `tests/.../test_route_declarations_under_pinned_fastapi.py` (#290) now
models that one assert, and `scripts/check_pinned_import.sh` (#292) loads the app
under the real pin -- but both were written *after* the bug, and both address
route declarations specifically. The condition that produced it is still here and
still unmeasured: the tests do not run what ships.

`pytest-subtests` is the sharpest illustration, because it is the tool that
produces the repository's own headline number. pytest 9.0.3 absorbed subtests
into core (`_pytest/subtests.py`); the standalone plugin the pins ask for is not
installed here at all. So "4797 subtests passed" is generated by one
implementation locally and a different one in the image. Nobody chose that, and
until this file nobody could see it.

## What this checks, and what it deliberately does not

It compares pinned version strings against `importlib.metadata` in the
interpreter that runs it. It says nothing about *whether* a given drift changes
behaviour -- that is unknowable without running both. It cannot: the point is
that the difference is invisible, so the honest output is the difference itself,
plus a verdict about which pins are the kind that this repository has evidence
can break at import time.

Version strings are compared literally. `1.14.0` and `1.14` are reported as
drift even though they install the same code, because the alternative is a
version parser this tree does not pin -- the same reason
`services/api/tests/test_declared_deps_reach_ci.py` gives for not comparing
ranges, in the paragraph naming what it does not cover. A false
"drift" costs a line of output; a false "match" costs the thing this file exists
to catch.

Exit codes, matching scripts/gate.sh:
  0  no drift among the import-critical pins
  1  at least one import-critical pin differs from what is installed
  2  the check could not run at all -- never a silent pass
"""

from __future__ import annotations

import argparse
import importlib.metadata as md
import json
import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
REQUIREMENTS = REPO_ROOT / "services" / "api" / "requirements-dev.txt"

# Pins whose version can change behaviour *before any assertion runs* -- at
# import, at route registration, at mapper configuration, at migration render.
# Drift in these is what makes a green suite unable to speak for the image.
#
# Every name here is on the list because of a recorded incident or because it is
# the layer directly under one:
#
#   fastapi     #288: `assert is_body_allowed_for_status_code` at registration.
#               0.115.6 refused to import the app, 0.135.3 accepted it.
#   starlette   the routing and middleware layer fastapi registers onto; the
#               same class of failure lives one import deeper.
#   pydantic    builds models at import. The team has already been bitten by
#               response models silently coercing types between versions.
#   sqlalchemy  configures mappers at import; `tests/postgres` is the only proof
#               of any SQL in this repository and it is worth nothing if the
#               mapper that ran is not the mapper that ships.
#   alembic     renders migrations. The FK-name-over-63-characters bug in
#               CLAUDE.md is a migration-render failure, invisible to pytest.
#   pytest      the runner itself.
#   pytest-subtests  measured 2026-08-30: absorbed into pytest 9 core, so the
#               plugin the pins name is not installed here, and the subtest
#               count in every report comes from different software than ships.
#
# Deliberately NOT here: jinja2, segno, uvicorn, psycopg. Drift in those is
# reported as information but does not by itself invalidate a green suite --
# they are exercised by assertions rather than by import, so a test that passes
# has actually observed their behaviour.
IMPORT_CRITICAL = frozenset(
    {
        "fastapi",
        "starlette",
        "pydantic",
        "sqlalchemy",
        "alembic",
        "pytest",
        "pytest-subtests",
    }
)

# `name==version`, ignoring comments, blank lines, markers and extras. Anything
# that is not a plain pin (a range, a URL, an `-r` include) is skipped rather
# than guessed at -- see the module docstring on literal comparison.
PIN_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)\s*==\s*([^\s;#]+)")


def normalise(name: str) -> str:
    """PEP 503 normalisation, so `pytest_subtests` and `pytest-subtests` agree."""

    return re.sub(r"[-_.]+", "-", name).lower()


def read_pins(path: pathlib.Path) -> dict[str, str]:
    """Every `name==version` line in a requirements file, normalised."""

    pins: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        match = PIN_RE.match(line)
        if match:
            pins[normalise(match.group(1))] = match.group(2).strip()
    return pins


def installed_version(name: str) -> str | None:
    """What this interpreter would import, or None if it could not import it."""

    try:
        return md.version(name)
    except md.PackageNotFoundError:
        return None


def survey(pins: dict[str, str]) -> list[dict[str, object]]:
    """One record per pin: what ships, what is here, and whether that matters."""

    rows: list[dict[str, object]] = []
    for name in sorted(pins):
        pinned = pins[name]
        found = installed_version(name)
        if found is None:
            state = "absent"
        elif found == pinned:
            state = "match"
        else:
            state = "drift"
        rows.append(
            {
                "name": name,
                "pinned": pinned,
                "installed": found,
                "state": state,
                "critical": name in IMPORT_CRITICAL,
            }
        )
    return rows


def critical_offenders(rows: list[dict[str, object]]) -> list[dict[str, object]]:
    """Import-critical pins that this interpreter does not actually have."""

    return [r for r in rows if r["critical"] and r["state"] != "match"]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Compare the pins that ship against the versions installed in the "
            "interpreter running this script."
        )
    )
    parser.add_argument(
        "--requirements",
        type=pathlib.Path,
        default=REQUIREMENTS,
        help="requirements file to read pins from (default: services/api/requirements-dev.txt)",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="emit the survey as JSON for a caller rather than a reader",
    )
    parser.add_argument(
        "--names-only",
        action="store_true",
        help="print only the import-critical names that drifted, one per line",
    )
    args = parser.parse_args(argv)

    if not args.requirements.is_file():
        print(f"không đọc được {args.requirements}", file=sys.stderr)
        return 2

    pins = read_pins(args.requirements)
    if not pins:
        # A requirements file with no `name==version` line at all is far more
        # likely to be a path mistake or a parser regression than a real state.
        # Reporting "no drift" here would be this gate's own silent-pass bug.
        print(f"không tìm thấy pin nào trong {args.requirements}", file=sys.stderr)
        return 2

    rows = survey(pins)
    offenders = critical_offenders(rows)

    if args.json:
        print(json.dumps({"rows": rows, "critical_drift": len(offenders)}, indent=2))
        return 1 if offenders else 0

    if args.names_only:
        for row in offenders:
            print(row["name"])
        return 1 if offenders else 0

    matched = [r for r in rows if r["state"] == "match"]
    drifted = [r for r in rows if r["state"] == "drift"]
    absent = [r for r in rows if r["state"] == "absent"]

    # Relative when it is inside the tree, absolute when it is not. `--requirements`
    # accepts any path, and `relative_to` raises rather than falling back, so the
    # unguarded form crashed the whole check on a file outside the repo.
    try:
        shown = args.requirements.resolve().relative_to(REPO_ROOT)
    except ValueError:
        shown = args.requirements

    print(f"pin đọc từ {shown}: {len(rows)}")
    print(f"python đang chạy: {sys.executable}")
    print(f"KHỚP {len(matched)}   LỆCH {len(drifted)}   THIẾU {len(absent)}")

    if drifted or absent:
        print()
        print("Bản cài trên máy này KHÁC bản sẽ ship:")
        for row in drifted + absent:
            mark = "  [quan trọng]" if row["critical"] else ""
            got = row["installed"] or "KHÔNG CÀI"
            print(f"  {row['name']:22} ship {row['pinned']:12} máy {got}{mark}")

    if not offenders:
        print()
        print("Không pin quan trọng nào lệch — bộ test đã chạy đúng bản sẽ ship.")
        return 0

    print()
    print("LỆCH Ở PIN QUAN TRỌNG. Những thư viện này quyết định hành vi TRƯỚC KHI")
    print("một assertion nào chạy được — lúc import, lúc đăng ký route, lúc dựng")
    print("mapper, lúc render migration. Một lượt pytest xanh trên bản khác KHÔNG")
    print("nói được gì về ảnh sẽ ship.")
    print()
    print("Đây chính là điều kiện đã tạo ra #288: 2305 ca xanh, container không")
    print("import nổi app. Cách đóng khoảng cách, rẻ (khoảng 2 giây):")
    print("    scripts/gate.sh pinned-import")
    return 1


if __name__ == "__main__":
    sys.exit(main())
