"""Sinh ô chất liệu «mực in» cho con dấu (UI v2, ADR-0020).

Hai ô `vai-bia.png` / `giay-trang.png` đã ghim từ lô sửa 1; script này thêm ô thứ ba
`muc-in.png`: nhiễu đậm đen/trắng để phá mặt coral của con dấu như mực cao su
in không đều. Thuần thủ tục, seed cố định, không ảnh chụp, không dữ liệu thật.
Chạy lại phải ra đúng từng byte (RNG của Python theo seed), rồi ghim lại digest
trong `.repo-guard-allowlist.json` nếu đổi tham số.

    python3 scripts/sinh_chat_lieu_ui_v2.py            # ghi apps/mobile/assets/textures/muc-in.png
    python3 scripts/sinh_chat_lieu_ui_v2.py --kiem     # chỉ in số đo, không ghi
"""

from __future__ import annotations

import pathlib
import random
import sys

from PIL import Image, ImageStat
from PIL.PngImagePlugin import PngInfo

ROOT = pathlib.Path(__file__).resolve().parents[1]
DICH = ROOT / "apps/mobile/assets/textures/muc-in.png"
SEED = 20260905
CANH = 256
# Coverage and alpha chosen so that at opacity 0.32 over coral (#fb693e) the
# composite has a standard deviation of about eight levels: the same order as
# the cloth on the cover, which is what reads as material at 1x.
DO_PHU = 0.55
ALPHA = (28, 110)


def sinh() -> Image.Image:
    rng = random.Random(SEED)
    anh = Image.new("RGBA", (CANH, CANH), (0, 0, 0, 0))
    px = anh.load()
    for y in range(CANH):
        for x in range(CANH):
            if rng.random() >= DO_PHU:
                continue
            sang = rng.random() < 0.5
            a = rng.randint(*ALPHA)
            px[x, y] = (255, 255, 255, a) if sang else (0, 0, 0, a)
    # A few short fibres, like the cloth has, so the noise is not pure static.
    for _ in range(90):
        x0, y0 = rng.randrange(CANH), rng.randrange(CANH)
        dai = rng.randint(6, 18)
        huong = rng.choice([(1, 0), (0, 1), (1, 1), (1, -1)])
        a = rng.randint(40, 90)
        for i in range(dai):
            x, y = (x0 + huong[0] * i) % CANH, (y0 + huong[1] * i) % CANH
            px[x, y] = (0, 0, 0, a)
    return anh


def do_tren_coral(anh: Image.Image, opacity: float = 0.32) -> float:
    """Standard deviation of the red channel after compositing at `opacity` over coral."""
    r, g, b, a = anh.split()
    a = a.point(lambda v: int(v * opacity))
    lop = Image.merge("RGBA", (r, g, b, a))
    nen = Image.new("RGBA", anh.size, (0xFB, 0x69, 0x3E, 255))
    return ImageStat.Stat(Image.alpha_composite(nen, lop).convert("RGB")).stddev[0]


def main(argv: list[str]) -> int:
    anh = sinh()
    st = ImageStat.Stat(anh)
    do = do_tren_coral(anh)
    print(f"muc-in: alpha mean {st.mean[3]:.1f}, stddev on coral @0.32 = {do:.2f}")
    if not 6.0 <= do <= 12.0:
        print("ngoài dải 6–12: chỉnh DO_PHU/ALPHA", file=sys.stderr)
        return 1
    if "--kiem" in argv:
        return 0
    meta = PngInfo()
    meta.add_text(
        "Comment",
        "Rủ Đi UI v2 texture tile «mực in»: procedural black/white specks + short fibres, "
        f"Python random seed {SEED}, coverage {DO_PHU}, alpha {ALPHA[0]}-{ALPHA[1]}; "
        "generated by scripts/sinh_chat_lieu_ui_v2.py; no photograph, no personal data.",
    )
    DICH.parent.mkdir(parents=True, exist_ok=True)
    anh.save(DICH, pnginfo=meta, optimize=True)
    print("ghi", DICH.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
